export const ROLE = {
  OWNER: "OWNER",
  TEACHER: "TEACHER",
  STUDENT: "STUDENT"
};

export const GRADE_STATUS = {
  DRAFT: "DRAFT",
  FINALIZED: "FINALIZED"
}

export const REVIEW_REQUEST_STATUS = {
  ACCEPTED: "ACCEPTED",
  DENIED: "DENIED"
}